import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/layouts/navbar";
import { Footer } from "@/components/layouts/footer";
import { Backdrop } from "@/components/layouts/backdrop";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="relative flex flex-col min-h-screen ">
          <Navbar />
          <Backdrop />
          <div className="flex-1 text-center text-white mt-10 px-20 flex flex-col justify-center items-center relative z-10 ">
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
